"This is + a string";
"This is a string";
`This is a string`;
console.log("This is a string");
console.log("This is a string");
console.log("Hello " + "World", "Comma Separated value");
console.log("Hello" - "World");
console.log(5);
console.log("5");
console.log(5 + "Anything");
console.log("5" + "Anything");
console.log(5 + 5);
console.log(5 + "5");
console.log(10 + 10 + "10");
console.log("Any random thing" + " ANy random" + " Any any");
console.log("oiueg897645/*-+!@#%$&%^(");
console.log("#@%^*$(&%)");
